// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewNetCore.ConsoleApplicationEFCoreCodeFirst.Entities;

namespace ReviewNetCore.ConsoleApplicationEFCoreCodeFirst.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReviewNetCore.ConsoleApplicationEFCoreCodeFirst.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rodrigo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Max"
                        });
                });

            modelBuilder.Entity("ReviewNetCore.ConsoleApplicationEFCoreCodeFirst.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int(11)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasName("Book_FK_Author_idx");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Review",
                            Name = "Asp.Net Core Review"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "SPA",
                            Name = "Angular 8"
                        });
                });

            modelBuilder.Entity("ReviewNetCore.ConsoleApplicationEFCoreCodeFirst.Entities.Book", b =>
                {
                    b.HasOne("ReviewNetCore.ConsoleApplicationEFCoreCodeFirst.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .HasConstraintName("Book_FK_Author");
                });
#pragma warning restore 612, 618
        }
    }
}
